#if: tag IS present
dist: xenial
language: minimal
sudo: required
addons:
  apt:
    packages:
    - p7zip-full
    - mtools
    - jq
    - u-boot-tools
    - html-xml-utils
    - squashfs-tools
    - bsdtar
    - axel
script:
- make build_armbian=y build_libreelec=n build_archlinux=n build
- ls -l output
deploy:
  provider: releases
  api_key: "a73b63c6bf49803463287f9f43c3e88c614ec5f4"
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: output/*.xz
  on:
    repo: silime/build-beikeyun
    tags: true
